CREATE SCHEMA `portfolio_manager` ;
USE `portfolio_manager`;

CREATE TABLE `COUNTRY` (
    `ID` INT,
    `CODE` VARCHAR(255) NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `ORGANIZATION` (
    `ID` INT,
    `NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    `COUNTRY_ID` INT NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `OPERATING_ENTITY` (
    `ID` INT,
    `NAME` VARCHAR(255) NOT NULL,
    `ORGANISATION_ID` INT NOT NULL,
    `COUNTRY_ID` INT NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `SERVICE_OFFERING` (
    `ID` INT,
    `NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    `BUSINESS_WEIGHTAGE` INT,
    `OPERATING_ENTITY_ID` INT NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `PORTFOLIO` (
    `ID` INT,
    `NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    `SOLUTION` VARCHAR(255),
    `PORTFOLIO_MODEL` VARCHAR(255),
    `BUSINESS_WEIGHTAGE` INT,
    `SERVICE_OFFERING_ID` INT NOT NULL,
    PRIMARY KEY (`ID`)
);
