CREATE SCHEMA `portfolio_manager` ;
USE `portfolio_manager`;

CREATE TABLE `COUNTRY` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    `CODE` VARCHAR(255) NOT NULL,
    `NAME` VARCHAR(255) NOT NULL
);

CREATE TABLE `ORGANIZATION` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    `COUNTRY_ID` BIGINT UNSIGNED NOT NULL
);

CREATE TABLE `OPERATING_ENTITY` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
    `ORGANISATION_ID` BIGINT UNSIGNED NOT NULL,
    `COUNTRY_ID` BIGINT UNSIGNED NOT NULL
);

CREATE TABLE `SERVICE_OFFERING` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    `BUSINESS_WEIGHTAGE` INT,
    `OPERATING_ENTITY_ID` BIGINT UNSIGNED NOT NULL
);

CREATE TABLE `PORTFOLIO` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    `SOLUTION` VARCHAR(255),
    `PORTFOLIO_MODEL` VARCHAR(255),
    `BUSINESS_WEIGHTAGE` INT,
    `SERVICE_OFFERING_ID` BIGINT UNSIGNED NOT NULL
);

CREATE TABLE `KPI_MASTER` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
	`NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` VARCHAR(255)
);

CREATE TABLE `KPI` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
	`THRESHOLD_MAX` INT,
	`THRESHOLD_MIN` INT,
	`KPI_MASTER_ID` BIGINT UNSIGNED,
	`PROJECT_ID` BIGINT UNSIGNED,
    `BUSINESS_WEIGHTAGE` INT
);

CREATE TABLE `KPI_DATA` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
	`VALUE` INT,
	`REPORTING_PERIOD` DATETIME,
	`COMMENTS` VARCHAR(255),
	`KPI_MASTER_ID` BIGINT UNSIGNED,	
    `KPI_ID` BIGINT UNSIGNED
);

CREATE TABLE `PROJECT` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
	`HEAD_COUNT` INT,
    `BUSINESS_WEIGHTAGE` INT,
    `DEVELOPMENT_METHODOLOGY` VARCHAR(255),
	`PORTFOLIO_ID` BIGINT UNSIGNED
);