ALTER TABLE `COUNTRY` ADD UNIQUE (CODE, NAME);
ALTER TABLE `ORGANIZATION` ADD UNIQUE (NAME, COUNTRY_ID);

ALTER TABLE `ORGANIZATION` ADD FOREIGN KEY (`COUNTRY_ID`) REFERENCES `COUNTRY` (`ID`);
ALTER TABLE `OPERATING_ENTITY` ADD FOREIGN KEY (`COUNTRY_ID`) REFERENCES `COUNTRY` (`ID`);
ALTER TABLE `OPERATING_ENTITY` ADD FOREIGN KEY (`ORGANISATION_ID`) REFERENCES `ORGANIZATION` (`ID`);
ALTER TABLE `SERVICE_OFFERING` ADD FOREIGN KEY (`OPERATING_ENTITY_ID`) REFERENCES `OPERATING_ENTITY` (`ID`);
ALTER TABLE `PORTFOLIO` ADD FOREIGN KEY (`SERVICE_OFFERING_ID`) REFERENCES `SERVICE_OFFERING` (`ID`);
ALTER TABLE `PROJECT` ADD FOREIGN KEY (`PORTFOLIO_ID`) REFERENCES `PORTFOLIO` (`ID`);
ALTER TABLE `KPI` ADD FOREIGN KEY (`KPI_MASTER_ID`) REFERENCES `KPI_MASTER` (`ID`);
ALTER TABLE `KPI` ADD FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`ID`);
ALTER TABLE `KPI_DATA` ADD FOREIGN KEY (`KPI_MASTER_ID`) REFERENCES `KPI_MASTER` (`ID`);
ALTER TABLE `KPI_DATA` ADD FOREIGN KEY (`KPI_ID`) REFERENCES `KPI` (`ID`);
