ALTER TABLE `COUNTRY` ADD UNIQUE (CODE, NAME);
ALTER TABLE `ORGANIZATION` ADD UNIQUE (NAME, COUNTRY_ID);

ALTER TABLE `ORGANIZATION` ADD FOREIGN KEY (`COUNTRY_ID`) REFERENCES `COUNTRY` (`ID`);
ALTER TABLE `OPERATING_ENTITY` ADD FOREIGN KEY (`COUNTRY_ID`) REFERENCES `COUNTRY` (`ID`);
ALTER TABLE `OPERATING_ENTITY` ADD FOREIGN KEY (`ORGANISATION_ID`) REFERENCES `ORGANIZATION` (`ID`);
ALTER TABLE `SERVICE_OFFERING` ADD FOREIGN KEY (`OPERATING_ENTITY_ID`) REFERENCES `OPERATING_ENTITY` (`ID`);
ALTER TABLE `PORTFOLIO` ADD FOREIGN KEY (`SERVICE_OFFERING_ID`) REFERENCES `SERVICE_OFFERING` (`ID`);
