INSERT INTO COUNTRY(ID, CODE, NAME) VALUES (1, 'DE', 'Germany');
INSERT INTO COUNTRY(ID, CODE, NAME) VALUES (2, 'GB', 'UK');
INSERT INTO COUNTRY(ID, CODE, NAME) VALUES (3, 'USA', 'USA');
INSERT INTO COUNTRY(ID, CODE, NAME) VALUES (4, 'IN', 'India');

INSERT INTO ORGANIZATION(ID, NAME, DESCRIPTION, COUNTRY_ID) VALUES (1, 'Allianz Technology India', 'Az India', 4);
INSERT INTO ORGANIZATION(ID, NAME, DESCRIPTION, COUNTRY_ID) VALUES (2, 'Allianz Technology Germany', 'Az Germany', 1);

INSERT INTO OPERATING_ENTITY(ID, NAME, ORGANISATION_ID, COUNTRY_ID) VALUES (1, 'Az Deu', 2, 1);

INSERT INTO SERVICE_OFFERING(ID, NAME, DESCRIPTION, BUSINESS_WEIGHTAGE, OPERATING_ENTITY_ID) VALUES (1, 'AD&M', 'Application Development and Maintenance', 40, 1);

INSERT INTO PORTFOLIO(ID, NAME, DESCRIPTION, SOLUTION, PORTFOLIO_MODEL, BUSINESS_WEIGHTAGE, SERVICE_OFFERING_ID) VALUES (1, 'ABBS', 'ABBS for Deu', 'ABS', 'Staff Augumentation', 70, 1);

INSERT INTO PROJECT(ID, NAME, HEAD_COUNT, BUSINESS_WEIGHTAGE, DEVELOPMENT_METHODOLOGY, PORTFOLIO_ID) VALUES (1, "Life", 7, 30, "Scrum", 1);